version: "3.5"
services:
  ngzero:
    image: localhost:5000/ngzero
    ports:
      - "82:80"
    networks:
      - ngzero
      - common
    volumes:
      - "~/dev/docker/projects/ngzero/volumes/code/dist:/usr/bin/ngzero/www"
      - "~/dev/docker/projects/common/volumes/logs:/usr/bin/apache/logs"
    environment:
      HOST_USER_ID: ${CURRENT_UID}
      HOST_GROUP_ID: ${CURRENT_GID}      
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3 
        window: 10s
    healthcheck:
      test: curl --fail http://localhost/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3  
networks:
  ngzero:  
    name: ngzero
  common:
    external: true
    name: common
