version: "3.1"
services:
  ngzero:
    image: localhost:5000/ngzero
    ports:
      - "81:80"
    networks:
      - ngzero
    volumes:
      - "~/dev/docker/projects/ngzero/volumes/code/dist:/usr/bin/ngzero/www"
      - "~/dev/docker/projects/ngzero/volumes/logs:/usr/bin/apache/logs"
    environment:
      HOST_USER_ID: ${CURRENT_UID}
      HOST_GROUP_ID: ${CURRENT_GID}      
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3 
        window: 10s
    healthcheck:
      test: curl --fail http://localhost/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3  
  logrotate:
    image: localhost:5000/logrotate
    networks:
      - ngzero      
    volumes:
      - "~/dev/docker/projects/ngzero/volumes/logs:/usr/bin/logrotate/logs"
networks:
  ngzero:  
