version: "3.5"
services:
  musicng:
    image: localhost:5000/musicng
    ports:
      - "82:80"
      - "84:443"
    networks:
      - musicng
      - common
    volumes:
      - "~/dev/docker/projects/musicng/volumes/code/dist:/usr/local/musicng/www"
      - "~/dev/docker/projects/common/volumes/logs:/usr/local/apache/logs"
      - "~/dev/docker/projects/common/volumes/letsencrypt/certbot/conf/live/thalasoft.com:/usr/local/musicng/letsencrypt"        
    environment:
      HOST_USER_ID: ${CURRENT_UID}
      HOST_GROUP_ID: ${CURRENT_GID}      
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3 
        window: 10s
    healthcheck:
      test: curl --fail http://localhost/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3  
networks:
  musicng:  
    name: musicng
  common:
    external: true
    name: common
